# Generated by Django 3.2.7 on 2022-12-05 19:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_linkitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='duedate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
